# Generated by Django 4.0.3 on 2022-04-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_alter_friend_age_alter_friend_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='birthday',
            field=models.DateField(verbose_name='生年月日'),
        ),
    ]
