# Generated by Django 4.0.3 on 2022-04-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_alter_friend_birthday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friend',
            options={'verbose_name_plural': 'おともだち'},
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('tag', models.ManyToManyField(to='friends.friend', verbose_name='紐づくタグ')),
            ],
        ),
    ]
