# Generated by Django 4.0.3 on 2022-04-21 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0005_alter_friend_options_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': '投票'},
        ),
    ]
