# Generated by Django 4.0.3 on 2022-04-21 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0006_alter_post_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
